-- Phase 3: Scenario Expansion
-- Adds expanded_content column to scripts table for storing child-facing narrative

ALTER TABLE scripts
ADD COLUMN IF NOT EXISTS expanded_content JSONB;

ALTER TABLE scripts
ADD COLUMN IF NOT EXISTS qa_score INT;

ALTER TABLE scripts
ADD COLUMN IF NOT EXISTS qa_score_retry INT;

COMMENT ON COLUMN scripts.expanded_content IS
'Expanded child-facing narrative per scene. Structure: { scenes: [{ scene_number, expanded_narrative }] }. Generated by GPT-4o from approved script. Null until scenario expansion step runs.';

COMMENT ON COLUMN scripts.qa_score IS
'QA score (1–10) of the first story generation attempt. Scores < 8 triggered a retry.';

COMMENT ON COLUMN scripts.qa_score_retry IS
'QA score (1–10) of the retry attempt. Null if no retry was needed. Compare with qa_score to see if retry improved quality. Both < 8 = retry did not fix the issue — worth manual review.';
