-- Phase 3: Scenario Expansion
-- Adds expanded_content column to scripts table for storing child-facing narrative

ALTER TABLE scripts
ADD COLUMN IF NOT EXISTS expanded_content JSONB;

COMMENT ON COLUMN scripts.expanded_content IS
'Expanded child-facing narrative per scene. Structure: { scenes: [{ scene_number, expanded_narrative }] }. Generated by GPT-4o from approved script. Null until scenario expansion step runs.';
